### ISSUE TITLE
Allow redirects to activate a prerender

### ISSUE THREAD

**Issue by domfarolino** [jeremyroman/alternate-loading-modes#17]
As per the current spec's [Allowing activation in place of navigation](https://htmlpreview.github.io/?https://raw.githubusercontent.com/jeremyroman/alternate-loading-modes/spec/index.html#navigate-activation) section, we modify the HTML Standard's navigation algorithm to activate prerenders early on, however if the navigation later redirects, we should probably re-check the activation conditions? If that's the case I'm happy to update the spec accordingly.

We've also discussed more generally what effect redirects have on prerendering, and the current idea is that the URL used for activation of a prerendering browsing context will be the "initial" prerendering URL that was used to instantiate the prerendering browsing context, as per https://docs.google.com/document/d/1E82ZqXibjCvpPdOgMmOfPIatPMEBVAiJ2KQm6r1_E94/edit#heading=h.soo6uwz4i3m. This is orthogonal to what this issue tracks, which is allowing us to obtain the URL-to-activate via a navigation redirect. Also it appears that the spec already supports the activation URL being the prerendering browsing context's _`startingURL`_, so I think we're all set on that front.

**Comment by domenic** [comment]
> if the navigation later redirects, we should probably re-check the activation conditions?

Which conditions are you referring to specifically? In particular, how could a redirect impact them?

**Comment by domfarolino** [comment]
Sorry, I was referring to the activation conditions. Redirects update the navigation URL and potentially the referrer policy, so should we re-check the document’s prerendering browsing context map to see if we can activate a prerender instead of going back to network?

We only seem to check this map once at the beginning of the navigation algorithm, but not after redirects.

**Comment by domenic** [comment]
Ah, I see. So the scenario is

```
<link rel="prerender2" href="https://example.org/a">

<a href="https://example.org/redirect-to-a">Click me</a>
```

With the current spec, we would not be able to use the prerendered `https://example.org/a` document. But with your proposal, we would. Very interesting.

I think the simplicity of the current version, where there's a one to one correspondence between `<link>`s (or other triggers) and `<a>`s, is nice. In fact, this seems pretty related to the discussion in the linked document, at least from the perspective of "what experiences do we want to support" and "what do authors have to do to get prerendering to work".

It would be pretty easy to add from the spec perspective, though, so I'm open to changing it.

**Comment by domfarolino** [comment]
Exactly. Yeah most of the discussion so far around activation matching and "what kind of experiences we want to support" seem to have been around how we handle redirects (and the matching of redirects) for prerendered resources, but I don't think we've discussed the other side of it, which is handling redirects in the URL that we use to activate it.

Before changing the spec, which I am indeed inclined to do, I'd like to get @mfalken 's thoughts as to what our implementation might do in this case.

**Comment by mfalken** [comment]
I think the current implementation does not support activating a prerender after a redirect. We only check at the beginning and if so we skip network loading. I expect that implementation-wise we could possibly make it work, but I'm not totally sure on the implementation cost.
