### ISSUE TITLE
Ensure the configuration <script> is subject to Content Security Policy

### ISSUE THREAD

**Issue by arturjanc** [jeremyroman/alternate-loading-modes#48]
Since the current proposal is using `<script>` elements to deliver the speculation configuration, please make sure that the script will be checked against the [_Should element’s inline type behavior be blocked by Content Security Policy_](https://w3c.github.io/webappsec-csp/#should-block-inline) algorithm in HTML.

The import maps spec may have some pointers for how to do this in https://wicg.github.io/import-maps/#integration-prepare-a-script

See also https://github.com/w3c/webappsec-csp/issues/472

**Comment by mfalken** [comment]
Based on the discussion and resolution at https://github.com/w3c/webappsec-csp/issues/472, is there any work to do here? Maybe just add a non-normative note like import-maps does and ensure we have WPT for this? (though with speculationrules it's not easy to test whether the configuration was processed).

**Comment by arturjanc** [comment]
Based on the discussion in w3c/webappsec-csp#472 my guess is that speculation configuration is a _processing model_, so based on the current CSP algorithm the `<script>` node would be subject to CSP (and would need to have the right nonce/hash or `'unsafe-inline'` in the policy). If so, I don't think there's anything to do here -- thanks for taking a look!
