### ISSUE TITLE
cross-origin-isolated

### ISSUE THREAD

**Issue by mfalken** [jeremyroman/alternate-loading-modes#52]
Regarding cross-origin-isolated listed here https://docs.google.com/document/d/1zY15k_wFTik2EoxBf3_RT7YjYpFMDaeNspy15n0rtww/edit#heading=h.quqnnky5hko for #42 .

I think it can probably just be allowed. Chromium's implementation is not planning to do any special casing of prerendered processes. The prerendered page will just get a normal process in the same way as a normal page, so cross-origin-isolated should just work as normal, unless I'm missing something. cc @domenic

**Comment by domenic** [comment]
I agree with that. I think maybe I was more concerned about it when I thought we'd be treating all policy-controlled features in some uniform way. As #42 and related PRs have revealed, we instead need individual patches for each. So we'll just not patch any of the "allowed to use" checks for cross-origin isolated.

**Comment by domenic** [comment]
Let's close this and cite it when ticking the box in #42.
