### ISSUE TITLE
execCommand('copy')

### ISSUE THREAD

**Issue by mfalken** [jeremyroman/alternate-loading-modes#54]
At https://chromium-review.googlesource.com/c/chromium/src/+/2755990, it looks like execCommand('copy') is able to modify the system clipboard without asking for permission, and is a sync API that results in a sync IPC. We are changing Chromium internals to cancel prerendering when this happens. But perhaps the spec should just throw an error if 'copy' is used during prerendering?

Or, we could consider it similar to a storage API, and grant access in the spec. It's a bit odd that the Async Clipboard API and execCommand seem to have different permission requirements in Chromium.

**Comment by mfalken** [comment]
cc @Clqsin45 @nhiroki may have more context.

**Comment by jeremyroman** [comment]
I'm actually kind of surprised this doesn't require user activation. Regardless, it seems to me like we should be able to get away with just dropping this on the floor, even if we don't want to throw an exception. I don't know what legitimate use cases there are for updating the clipboard on load, and in any case anything else on the system could have written to the clipboard in the meantime, so it's not like content doesn't already need to be prepared for this -- except for the case where the user genuinely expects to have their clipboard updated on load (in which case I suppose we could buffer this until load, but that seems weird to me).

**Comment by Clqsin45** [comment]
Since `document.execCommand('copy');` on a prerendering page returns `true`, I guess it does not check whether the browsing context is active nor whether the page has `clipboardWrite` permission. 

ps: I find a chromium issue[1], but it hasn't been fixed yet. 
[1] document.execCommand('copy') should require https / secure context, https://crbug.com/978228

**Comment by Clqsin45** [comment]
`EvalJs` and `ExecJs` run with a user gesture by default, and the fake user activation allows the prerendering page to access the clipboard.
Sorry, it should be a test bug, after setting the option to `EXECUTE_SCRIPT_NO_USER_GESTURE`, `execCommand('copy')` returns false.

**Comment by jeremyroman** [comment]
It sounds like there is no spec issue here then, is that right? Closing; reopen if I misunderstood.
