### ISSUE TITLE
Clarify prerendering documents cannot have focus. 

### ISSUE THREAD

**Issue by Clqsin45** [jeremyroman/alternate-loading-modes#55]
Some APIs's specs[1][2] require documents to have focus[3] when using these APIs. So for prerendering,  maybe we should clarify that prerendering documents cannot be focused and executing `document.hasFocus()` on these pages always returns `false`[4].

Maybe we should also clarify that prerendering browsing context cannot be active?  

cc: @nhiroki 

[1] https://w3c.github.io/clipboard-apis/#privacy-async
[2] https://www.w3.org/TR/pointerlock/#extensions-to-the-element-interface
[3] https://html.spec.whatwg.org/multipage/interaction.html#focus 
[4] https://chromium-review.googlesource.com/c/chromium/src/+/2743865/5..9/third_party/blink/web_tests/wpt_internal/prerender/resources/document-has-focus.html#b17

**Comment by domenic** [comment]
We only very recently added the concept of [system focus](https://html.spec.whatwg.org/#tlbc-system-focus) to the HTML spec. Although, we didn't hook it up to `document.hasFocus()`, hmm.

My take, based on previous discussions, is that prerendering browsing contexts can have their contents focused (e.g., they can have a nontrivial `document.activeElement`; `someElement.focus()` works; `autofocus=""` works). But, they cannot have system focus.

**Comment by a4sriniv** [comment]
I agree with @domenic, prerendering browsing contexts should behave the same as portals do currently (they don't have system focus and only get it on activation). See WICG/portals#257 for the portals discussion on focus.

**Comment by Clqsin45** [comment]
Thank you for discussing! 
I've added wpt-internal tests.

**Comment by mfalken** [comment]
Thanks @Clqsin45 for raising this. We could probably extend the section on Activation-gated APIs to also cover System Focus-gated APIs:
https://jeremyroman.github.io/alternate-loading-modes/#activation-gated

**Comment by mfalken** [comment]
It appears some APIs like Picture-In-Picture may also be gated on visibility state as well as user activation (e.g., https://w3c.github.io/picture-in-picture/#auto-pip can be used without user activation if visibility state changes??), so we may also add visibility state to this section. Filed related #59

**Comment by mfalken** [comment]
This is fixed in https://github.com/jeremyroman/alternate-loading-modes/pull/62 and the Clipboard case specifically in https://github.com/jeremyroman/alternate-loading-modes/pull/69. Thanks @Clqsin45  for raising this!
