### ISSUE TITLE
visibilityState for prerendering browsing contexts

### ISSUE THREAD

**Issue by mfalken** [jeremyroman/alternate-loading-modes#59]
Chromium's implementation is using `document.visibilityState == 'hidden'` for prerendering browsing contexts:
https://chromium-review.googlesource.com/c/chromium/src/+/2821563

We should make sure the impl and spec match here. cc @horo-t and @bokand does this match what you were planning here?

EDIT: typed too quickly, visibilityState == 'hidden' is what the test is using, not 'prerender'.

**Comment by bokand** [comment]
Yup, I think `visibilityState == 'hidden'` in a prerender makes sense. Though in a portal it may be visible.

It's stated a bit awkwardly with two `IF` statements and no else, but I think prerender already does the right thing following [the specified steps](https://www.w3.org/TR/page-visibility/#dfn-steps-to-determine-the-visibility-state). At least, it definitely shouldn't return "visible". Maybe we should add an explicit statement to the "hidden" branch for prerendering? @mfalken is that what you meant about spec or in prerendering specific specs?

**Comment by mfalken** [comment]
Makes sense, thanks. I mostly just wanted to make sure we're on the same page. Regarding spec language, if it's already implied by the Page Visibility spec, it could possibly just be a non-normative note in the prerendering spec. The Editor's Draft of the Page Visibility spec seems to have moved most of the cases to a non-normative note also: https://w3c.github.io/page-visibility/#visibility-states

**Comment by mfalken** [comment]
Fixed in https://github.com/jeremyroman/alternate-loading-modes/pull/62
